// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'score.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$NilaiImpl _$$NilaiImplFromJson(Map<String, dynamic> json) => _$NilaiImpl(
      key: json['key'] as String?,
      idKelas: json['id_kelas'] as String?,
      kelas: json['kelas'] as String?,
      namaLengkap: json['nama_lengkap'] as String?,
      nis: json['nis'] as String?,
      idMapel: json['id_mapel'] as String?,
      mapel: json['mapel'] as String?,
      idJenisPenilaian: json['id_jenis_penilaian'] as String?,
      nameJenisPenilaian: json['name_jenis_penilaian'] as String?,
      nilai: (json['nilai'] as num?)?.toInt(),
      date: json['date'] as String?,
      hari: json['hari'] as String?,
      jam: json['jam'] as String?,
      staff: json['staff'] as String?,
      pr1: json['pr1'] as String?,
      pr2: json['pr2'] as String?,
      pr3: json['pr3'] as String?,
      pr4: json['pr4'] as String?,
      rpr: (json['rpr'] as num?)?.toInt(),
      ph1: json['ph1'] as String?,
      ph2: json['ph2'] as String?,
      ph3: json['ph3'] as String?,
      ph4: json['ph4'] as String?,
      rph: json['rph'] as String?,
      t1: json['t1'] as String?,
      t2: json['t2'] as String?,
      t3: json['t3'] as String?,
      t4: json['t4'] as String?,
      rt: (json['rt'] as num?)?.toInt(),
      pts: json['pts'] as String?,
      pta: json['pta'] as String?,
      nilaiRapor: json['nilai_rapor'] as String?,
      kkm: json['kkm'] as String?,
      kedisiplinan: json['kedisiplinan'] as String?,
      kerapihan: json['kerapihan'] as String?,
      kebersihan: json['kebersihan'] as String?,
      keterangan: json['keterangan'] as String?,
      img: json['img'] as String?,
    );

Map<String, dynamic> _$$NilaiImplToJson(_$NilaiImpl instance) =>
    <String, dynamic>{
      'key': instance.key,
      'id_kelas': instance.idKelas,
      'kelas': instance.kelas,
      'nama_lengkap': instance.namaLengkap,
      'nis': instance.nis,
      'id_mapel': instance.idMapel,
      'mapel': instance.mapel,
      'id_jenis_penilaian': instance.idJenisPenilaian,
      'name_jenis_penilaian': instance.nameJenisPenilaian,
      'nilai': instance.nilai,
      'date': instance.date,
      'hari': instance.hari,
      'jam': instance.jam,
      'staff': instance.staff,
      'pr1': instance.pr1,
      'pr2': instance.pr2,
      'pr3': instance.pr3,
      'pr4': instance.pr4,
      'rpr': instance.rpr,
      'ph1': instance.ph1,
      'ph2': instance.ph2,
      'ph3': instance.ph3,
      'ph4': instance.ph4,
      'rph': instance.rph,
      't1': instance.t1,
      't2': instance.t2,
      't3': instance.t3,
      't4': instance.t4,
      'rt': instance.rt,
      'pts': instance.pts,
      'pta': instance.pta,
      'nilai_rapor': instance.nilaiRapor,
      'kkm': instance.kkm,
      'kedisiplinan': instance.kedisiplinan,
      'kerapihan': instance.kerapihan,
      'kebersihan': instance.kebersihan,
      'keterangan': instance.keterangan,
      'img': instance.img,
    };
